name: SG_svile
author: svile & Zeao
description: Survival plugin
main: svile\sw\SWmain
version: 0.7dev
api: [3.0.0-ALPHA4, 3.0.1]
load: STARTUP

commands:
 sg:
  description: Survival Games main command
